# Generated by Django 5.2.4 on 2025-07-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="token",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
