# Generated by Django 5.2.1 on 2025-05-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdvisoryMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="A short, descriptive title for the advisory.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="A detailed description of the advisory. This will be the 'Advisory Content'."
                    ),
                ),
                (
                    "suggestion",
                    models.TextField(
                        blank=True,
                        help_text="Recommended actions or suggestions. This will be the 'Recommendation'.",
                        null=True,
                    ),
                ),
                ("published_date", models.DateField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Seasonal", "Seasonal Advisory"),
                            ("Monthly", "Monthly Advisory"),
                        ],
                        default="Monthly",
                        help_text="Category of the advisory: Seasonal or Monthly.",
                        max_length=20,
                    ),
                ),
                (
                    "rainfall_forecast",
                    models.CharField(
                        blank=True,
                        help_text="Forecast regarding rainfall (e.g., 'Slightly above average').",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "temperature_outlook",
                    models.CharField(
                        blank=True,
                        help_text="Outlook regarding temperature (e.g., 'Mild during germination').",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "potential_risks",
                    models.TextField(
                        blank=True,
                        help_text="Potential risks associated with the advisory (e.g., 'Waterlogging in valley areas').",
                        null=True,
                    ),
                ),
                (
                    "featured_image_file",
                    models.FileField(
                        blank=True,
                        help_text="Optional featured image or file for the advisory.",
                        null=True,
                        upload_to="advisory_media/",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Advisory Message",
                "verbose_name_plural": "Advisory Messages",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the disease (e.g., Stem Rust).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="A general description of the disease."),
                ),
                (
                    "suggestion",
                    models.TextField(
                        blank=True,
                        help_text="Overall suggestion for dealing with the disease.",
                        null=True,
                    ),
                ),
                (
                    "causes",
                    models.TextField(
                        blank=True, help_text="Causes of the disease.", null=True
                    ),
                ),
                (
                    "treatment_options",
                    models.TextField(
                        blank=True, help_text="Available treatment options.", null=True
                    ),
                ),
                (
                    "prevention_methods",
                    models.TextField(
                        blank=True, help_text="Methods for prevention.", null=True
                    ),
                ),
                ("symptoms", models.TextField(help_text="Common symptoms observed.")),
                (
                    "affected_crops",
                    models.CharField(
                        help_text="Comma-separated list of affected crops (e.g., 'Wheat, Barley, Rye').",
                        max_length=255,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image representing the disease.",
                        null=True,
                        upload_to="disease_images/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disease",
                "verbose_name_plural": "Diseases",
                "ordering": ["name"],
            },
        ),
    ]
