# Generated by Django 5.2.1 on 2025-05-30 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info_hub", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="advisorymessage",
            old_name="description",
            new_name="advisory_content",
        ),
    ]
