# Generated by Django 4.2.9 on 2026-06-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info_hub", "0003_add_translation_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisorymessage",
            name="advisory_content_am",
            field=models.TextField(
                help_text="A detailed description of the advisory. This will be the 'Advisory Content'.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="advisory_content_en",
            field=models.TextField(
                help_text="A detailed description of the advisory. This will be the 'Advisory Content'.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="advisory_content_om",
            field=models.TextField(
                help_text="A detailed description of the advisory. This will be the 'Advisory Content'.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="advisory_content_ti",
            field=models.TextField(
                help_text="A detailed description of the advisory. This will be the 'Advisory Content'.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="potential_risks_am",
            field=models.TextField(
                blank=True,
                help_text="Potential risks associated with the advisory (e.g., 'Waterlogging in valley areas').",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="potential_risks_en",
            field=models.TextField(
                blank=True,
                help_text="Potential risks associated with the advisory (e.g., 'Waterlogging in valley areas').",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="potential_risks_om",
            field=models.TextField(
                blank=True,
                help_text="Potential risks associated with the advisory (e.g., 'Waterlogging in valley areas').",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="potential_risks_ti",
            field=models.TextField(
                blank=True,
                help_text="Potential risks associated with the advisory (e.g., 'Waterlogging in valley areas').",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="rainfall_forecast_am",
            field=models.CharField(
                blank=True,
                help_text="Forecast regarding rainfall (e.g., 'Slightly above average').",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="rainfall_forecast_en",
            field=models.CharField(
                blank=True,
                help_text="Forecast regarding rainfall (e.g., 'Slightly above average').",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="rainfall_forecast_om",
            field=models.CharField(
                blank=True,
                help_text="Forecast regarding rainfall (e.g., 'Slightly above average').",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="rainfall_forecast_ti",
            field=models.CharField(
                blank=True,
                help_text="Forecast regarding rainfall (e.g., 'Slightly above average').",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="suggestion_am",
            field=models.TextField(
                blank=True,
                help_text="Recommended actions or suggestions. This will be the 'Recommendation'.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="suggestion_en",
            field=models.TextField(
                blank=True,
                help_text="Recommended actions or suggestions. This will be the 'Recommendation'.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="suggestion_om",
            field=models.TextField(
                blank=True,
                help_text="Recommended actions or suggestions. This will be the 'Recommendation'.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="suggestion_ti",
            field=models.TextField(
                blank=True,
                help_text="Recommended actions or suggestions. This will be the 'Recommendation'.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="temperature_outlook_am",
            field=models.CharField(
                blank=True,
                help_text="Outlook regarding temperature (e.g., 'Mild during germination').",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="temperature_outlook_en",
            field=models.CharField(
                blank=True,
                help_text="Outlook regarding temperature (e.g., 'Mild during germination').",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="temperature_outlook_om",
            field=models.CharField(
                blank=True,
                help_text="Outlook regarding temperature (e.g., 'Mild during germination').",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="temperature_outlook_ti",
            field=models.CharField(
                blank=True,
                help_text="Outlook regarding temperature (e.g., 'Mild during germination').",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="title_am",
            field=models.CharField(
                help_text="A short, descriptive title for the advisory.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="title_en",
            field=models.CharField(
                help_text="A short, descriptive title for the advisory.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="title_om",
            field=models.CharField(
                help_text="A short, descriptive title for the advisory.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisorymessage",
            name="title_ti",
            field=models.CharField(
                help_text="A short, descriptive title for the advisory.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="causes_am",
            field=models.TextField(
                blank=True, help_text="Causes of the disease.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="causes_en",
            field=models.TextField(
                blank=True, help_text="Causes of the disease.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="causes_om",
            field=models.TextField(
                blank=True, help_text="Causes of the disease.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="causes_ti",
            field=models.TextField(
                blank=True, help_text="Causes of the disease.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="description_am",
            field=models.TextField(
                help_text="A general description of the disease.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="description_en",
            field=models.TextField(
                help_text="A general description of the disease.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="description_om",
            field=models.TextField(
                help_text="A general description of the disease.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="description_ti",
            field=models.TextField(
                help_text="A general description of the disease.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="name_am",
            field=models.CharField(
                help_text="Name of the disease (e.g., Stem Rust).",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="name_en",
            field=models.CharField(
                help_text="Name of the disease (e.g., Stem Rust).",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="name_om",
            field=models.CharField(
                help_text="Name of the disease (e.g., Stem Rust).",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="name_ti",
            field=models.CharField(
                help_text="Name of the disease (e.g., Stem Rust).",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="prevention_methods_am",
            field=models.TextField(
                blank=True, help_text="Methods for prevention.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="prevention_methods_en",
            field=models.TextField(
                blank=True, help_text="Methods for prevention.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="prevention_methods_om",
            field=models.TextField(
                blank=True, help_text="Methods for prevention.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="prevention_methods_ti",
            field=models.TextField(
                blank=True, help_text="Methods for prevention.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="suggestion_am",
            field=models.TextField(
                blank=True,
                help_text="Overall suggestion for dealing with the disease.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="suggestion_en",
            field=models.TextField(
                blank=True,
                help_text="Overall suggestion for dealing with the disease.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="suggestion_om",
            field=models.TextField(
                blank=True,
                help_text="Overall suggestion for dealing with the disease.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="suggestion_ti",
            field=models.TextField(
                blank=True,
                help_text="Overall suggestion for dealing with the disease.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="symptoms_am",
            field=models.TextField(help_text="Common symptoms observed.", null=True),
        ),
        migrations.AlterField(
            model_name="disease",
            name="symptoms_en",
            field=models.TextField(help_text="Common symptoms observed.", null=True),
        ),
        migrations.AlterField(
            model_name="disease",
            name="symptoms_om",
            field=models.TextField(help_text="Common symptoms observed.", null=True),
        ),
        migrations.AlterField(
            model_name="disease",
            name="symptoms_ti",
            field=models.TextField(help_text="Common symptoms observed.", null=True),
        ),
        migrations.AlterField(
            model_name="disease",
            name="treatment_options_am",
            field=models.TextField(
                blank=True, help_text="Available treatment options.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="treatment_options_en",
            field=models.TextField(
                blank=True, help_text="Available treatment options.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="treatment_options_om",
            field=models.TextField(
                blank=True, help_text="Available treatment options.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="treatment_options_ti",
            field=models.TextField(
                blank=True, help_text="Available treatment options.", null=True
            ),
        ),
    ]
