# Generated by Django 4.2.9 on 2026-07-05 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("info_hub", "0004_alter_advisorymessage_advisory_content_am_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisorymessage",
            name="advisory_pdf",
            field=models.FileField(
                blank=True,
                help_text="Optional original advisory document (PDF) as provided by the source (FR20).",
                null=True,
                upload_to="advisory_pdfs/",
            ),
        ),
        migrations.CreateModel(
            name="WheatCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Cluster name (e.g., 'Bale Wheat Cluster').",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Cluster name (e.g., 'Bale Wheat Cluster').",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "name_am",
                    models.CharField(
                        help_text="Cluster name (e.g., 'Bale Wheat Cluster').",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "name_om",
                    models.CharField(
                        help_text="Cluster name (e.g., 'Bale Wheat Cluster').",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "name_ti",
                    models.CharField(
                        help_text="Cluster name (e.g., 'Bale Wheat Cluster').",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="General information about the cluster."
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="General information about the cluster.",
                        null=True,
                    ),
                ),
                (
                    "description_am",
                    models.TextField(
                        blank=True,
                        help_text="General information about the cluster.",
                        null=True,
                    ),
                ),
                (
                    "description_om",
                    models.TextField(
                        blank=True,
                        help_text="General information about the cluster.",
                        null=True,
                    ),
                ),
                (
                    "description_ti",
                    models.TextField(
                        blank=True,
                        help_text="General information about the cluster.",
                        null=True,
                    ),
                ),
                (
                    "suitability_trend",
                    models.TextField(
                        blank=True,
                        help_text="Narrative of the wheat land suitability trend for this cluster (e.g., 'Highly suitable now; declines to moderately suitable by the 2050s under SSP5').",
                    ),
                ),
                (
                    "suitability_trend_en",
                    models.TextField(
                        blank=True,
                        help_text="Narrative of the wheat land suitability trend for this cluster (e.g., 'Highly suitable now; declines to moderately suitable by the 2050s under SSP5').",
                        null=True,
                    ),
                ),
                (
                    "suitability_trend_am",
                    models.TextField(
                        blank=True,
                        help_text="Narrative of the wheat land suitability trend for this cluster (e.g., 'Highly suitable now; declines to moderately suitable by the 2050s under SSP5').",
                        null=True,
                    ),
                ),
                (
                    "suitability_trend_om",
                    models.TextField(
                        blank=True,
                        help_text="Narrative of the wheat land suitability trend for this cluster (e.g., 'Highly suitable now; declines to moderately suitable by the 2050s under SSP5').",
                        null=True,
                    ),
                ),
                (
                    "suitability_trend_ti",
                    models.TextField(
                        blank=True,
                        help_text="Narrative of the wheat land suitability trend for this cluster (e.g., 'Highly suitable now; declines to moderately suitable by the 2050s under SSP5').",
                        null=True,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Administrative region (e.g., 'Oromia').",
                        max_length=255,
                    ),
                ),
                (
                    "geometry",
                    models.JSONField(
                        blank=True,
                        help_text="GeoJSON geometry (Polygon/MultiPolygon, WGS84 lon/lat) of the cluster boundary.",
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "diseases",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Major wheat diseases common in this cluster.",
                        related_name="clusters",
                        to="info_hub.disease",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wheat Cluster",
                "verbose_name_plural": "Wheat Clusters",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="advisorymessage",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                help_text="Wheat cluster this advisory targets (leave empty for a general advisory).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advisories",
                to="info_hub.wheatcluster",
            ),
        ),
    ]
