server {
    listen 80;

    location / {
        # This part handles the OPTIONS preflight requests
        if ($request_method = 'OPTIONS') {
            # Add CORS headers
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain; charset=UTF-8';
            add_header 'Content-Length' 0;
            return 204; # Return a 204 No Content response
        }

        # This passes all other requests to the Django backend
        proxy_pass http://django:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /mnt/volumes/statics/static/;
    }

    location /uploaded/ {
        alias /mnt/volumes/statics/uploaded/;
        autoindex on;
    }
}