# Generated by Django 4.2.9 on 2026-07-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0092_migrate and_remove_resourcebase_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="description_am",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="description_om",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="description_ti",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="license_text_am",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="license_text_om",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="license_text_ti",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="name_am",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="name_om",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="name_ti",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="name_am",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="name_om",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="name_ti",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="restrictioncodetype",
            name="description_am",
            field=models.TextField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="restrictioncodetype",
            name="description_om",
            field=models.TextField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="restrictioncodetype",
            name="description_ti",
            field=models.TextField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="restrictioncodetype",
            name="gn_description_am",
            field=models.TextField(
                max_length=255, null=True, verbose_name="GeoNode description"
            ),
        ),
        migrations.AddField(
            model_name="restrictioncodetype",
            name="gn_description_om",
            field=models.TextField(
                max_length=255, null=True, verbose_name="GeoNode description"
            ),
        ),
        migrations.AddField(
            model_name="restrictioncodetype",
            name="gn_description_ti",
            field=models.TextField(
                max_length=255, null=True, verbose_name="GeoNode description"
            ),
        ),
        migrations.AddField(
            model_name="spatialrepresentationtype",
            name="description_am",
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="spatialrepresentationtype",
            name="description_om",
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="spatialrepresentationtype",
            name="description_ti",
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="spatialrepresentationtype",
            name="gn_description_am",
            field=models.CharField(
                max_length=255, null=True, verbose_name="GeoNode description"
            ),
        ),
        migrations.AddField(
            model_name="spatialrepresentationtype",
            name="gn_description_om",
            field=models.CharField(
                max_length=255, null=True, verbose_name="GeoNode description"
            ),
        ),
        migrations.AddField(
            model_name="spatialrepresentationtype",
            name="gn_description_ti",
            field=models.CharField(
                max_length=255, null=True, verbose_name="GeoNode description"
            ),
        ),
        migrations.AddField(
            model_name="topiccategory",
            name="description_am",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="topiccategory",
            name="description_om",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="topiccategory",
            name="description_ti",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="topiccategory",
            name="gn_description_am",
            field=models.TextField(
                default="", null=True, verbose_name="GeoNode description"
            ),
        ),
        migrations.AddField(
            model_name="topiccategory",
            name="gn_description_om",
            field=models.TextField(
                default="", null=True, verbose_name="GeoNode description"
            ),
        ),
        migrations.AddField(
            model_name="topiccategory",
            name="gn_description_ti",
            field=models.TextField(
                default="", null=True, verbose_name="GeoNode description"
            ),
        ),
    ]
