# Generated by Django 4.2.9 on 2026-07-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0034_auto_20200512_1431"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupcategory",
            name="name_am",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="groupcategory",
            name="name_om",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="groupcategory",
            name="name_ti",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="groupprofile",
            name="description_am",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="groupprofile",
            name="description_om",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="groupprofile",
            name="description_ti",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="groupprofile",
            name="title_am",
            field=models.CharField(max_length=1000, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="groupprofile",
            name="title_om",
            field=models.CharField(max_length=1000, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="groupprofile",
            name="title_ti",
            field=models.CharField(max_length=1000, null=True, verbose_name="Title"),
        ),
    ]
