# Generated by Django 4.2.9 on 2026-07-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0043_auto_20230807_1234"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="abstract_am",
            field=models.TextField(
                blank=True,
                help_text="brief narrative summary of the content of the resource(s)",
                max_length=2000,
                null=True,
                verbose_name="abstract",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="abstract_om",
            field=models.TextField(
                blank=True,
                help_text="brief narrative summary of the content of the resource(s)",
                max_length=2000,
                null=True,
                verbose_name="abstract",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="abstract_ti",
            field=models.TextField(
                blank=True,
                help_text="brief narrative summary of the content of the resource(s)",
                max_length=2000,
                null=True,
                verbose_name="abstract",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="constraints_other_am",
            field=models.TextField(
                blank=True,
                help_text="other restrictions and legal prerequisites for accessing and using the resource or metadata",
                null=True,
                verbose_name="restrictions other",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="constraints_other_om",
            field=models.TextField(
                blank=True,
                help_text="other restrictions and legal prerequisites for accessing and using the resource or metadata",
                null=True,
                verbose_name="restrictions other",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="constraints_other_ti",
            field=models.TextField(
                blank=True,
                help_text="other restrictions and legal prerequisites for accessing and using the resource or metadata",
                null=True,
                verbose_name="restrictions other",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="data_quality_statement_am",
            field=models.TextField(
                blank=True,
                help_text="general explanation of the data producer's knowledge about the lineage of a dataset",
                max_length=2000,
                null=True,
                verbose_name="data quality statement",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="data_quality_statement_om",
            field=models.TextField(
                blank=True,
                help_text="general explanation of the data producer's knowledge about the lineage of a dataset",
                max_length=2000,
                null=True,
                verbose_name="data quality statement",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="data_quality_statement_ti",
            field=models.TextField(
                blank=True,
                help_text="general explanation of the data producer's knowledge about the lineage of a dataset",
                max_length=2000,
                null=True,
                verbose_name="data quality statement",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="purpose_am",
            field=models.TextField(
                blank=True,
                help_text="summary of the intentions with which the resource(s) was developed",
                max_length=500,
                null=True,
                verbose_name="purpose",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="purpose_om",
            field=models.TextField(
                blank=True,
                help_text="summary of the intentions with which the resource(s) was developed",
                max_length=500,
                null=True,
                verbose_name="purpose",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="purpose_ti",
            field=models.TextField(
                blank=True,
                help_text="summary of the intentions with which the resource(s) was developed",
                max_length=500,
                null=True,
                verbose_name="purpose",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="supplemental_information_am",
            field=models.TextField(
                default="No information provided",
                help_text="any other descriptive information about the dataset",
                max_length=2000,
                null=True,
                verbose_name="supplemental information",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="supplemental_information_om",
            field=models.TextField(
                default="No information provided",
                help_text="any other descriptive information about the dataset",
                max_length=2000,
                null=True,
                verbose_name="supplemental information",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="supplemental_information_ti",
            field=models.TextField(
                default="No information provided",
                help_text="any other descriptive information about the dataset",
                max_length=2000,
                null=True,
                verbose_name="supplemental information",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="title_am",
            field=models.CharField(
                help_text="name by which the cited resource is known",
                max_length=255,
                null=True,
                verbose_name="title",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="title_om",
            field=models.CharField(
                help_text="name by which the cited resource is known",
                max_length=255,
                null=True,
                verbose_name="title",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="title_ti",
            field=models.CharField(
                help_text="name by which the cited resource is known",
                max_length=255,
                null=True,
                verbose_name="title",
            ),
        ),
    ]
