# Generated by Django 4.2.9 on 2026-07-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0054_alter_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description_am",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="description_om",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="description_ti",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name_am",
            field=models.CharField(
                db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="name_om",
            field=models.CharField(
                db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="name_ti",
            field=models.CharField(
                db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
